version: "2"

checks:
  file-lines:
      enabled: false
  argument-count:
    config:
      threshold: 5

plugins:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true

exclude_patterns:
  - "docs/"
  - "stellar_base/xdr/"
  - "stellar_base/wordlist/"
  - "stellar_base/stellarxdr/"

