source "https://rubygems.org"
gem "xdrgen", git: "https://github.com/stellar/xdrgen", branch: "master"
# Ruby 3.4+ compatibility gems
gem "base64"
gem "benchmark"
gem "bigdecimal"
gem "logger"
gem "mutex_m"
