import pytest

from stellar_sdk.sep.exceptions import InvalidSep45ChallengeError
from stellar_sdk.sep.stellar_soroban_web_authentication import (
    ChallengeAuthorizationEntries,
)
from tests.sep.soroban_web_authentication.helpers import (
    CLIENT_CONTRACT_ACCOUNT,
    CLIENT_DOMAIN,
    CLIENT_DOMAIN_ACCOUNT,
    HOME_DOMAIN,
    NETWORK_PASSPHRASE,
    NONCE,
    SERVER_ACCOUNT,
    WEB_AUTH_CONTRACT,
    WEB_AUTH_DOMAIN,
    _verify_entries,
    build_valid_entries_with_client_domain,
)


async def test_verify_challenge_authorization_entries(soroban_server, rpc_mock):
    mock_data = {
        "jsonrpc": "2.0",
        "id": "36fff9ab2a3a4c3882845b5e26f3aa0a",
        "result": {
            "transactionData": "AAAAAAAAAAYAAAAAAAAAAAsFgywxsz4qQ0GCRAuou6p/ImgqqQ7mY7P2yFlmqm0zAAAAAAAAAACk2IqM8QZFSkGDUOf7zmoZrxaiw/Zj4MPjY7Grhfb7nQAAAAYAAAABaCSw4cnhsl4aWyRa5pYTz/CKYsGdDy0Idp1Kqpu4xucAAAAUAAAAAQAAAAYAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAAUAAAAAQAAAAcj000tCjHCGMjC/mKFK3Lht6v48nJut+fTPuaJMaiVaQAAAAeaeGC7WJkEo55dPPnhmm7ZJWc9cFqYV+zyj15sRkesdgAAAAMAAAAGAAAAAAAAAAALBYMsMbM+KkNBgkQLqLuqfyJoKqkO5mOz9shZZqptMwAAABUF/XrhgrGbmwAAAAAAAAAGAAAAAAAAAACk2IqM8QZFSkGDUOf7zmoZrxaiw/Zj4MPjY7Grhfb7nQAAABV74n9h5Cs9wwAAAAAAAAAGAAAAAWgksOHJ4bJeGlskWuaWE8/wimLBnQ8tCHadSqqbuMbnAAAAFSKLTxTml+dTAAAAAAAngZ4AAAEgAAAA4AAAAAAAAuDd",
            "events": [
                "AAAAAQAAAAAAAAAAAAAAAgAAAAAAAAADAAAADwAAAAdmbl9jYWxsAAAAAA0AAAAgpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAAPAAAAD3dlYl9hdXRoX3ZlcmlmeQAAAAARAAAAAQAAAAcAAAAPAAAAB2FjY291bnQAAAAADgAAADhDQlVDSk1IQlpIUTNFWFEyTE1TRlZaVVdDUEg3QkNUQ1lHT1E2TElJTzJPVVZLVTNYRERPTzJITgAAAA8AAAANY2xpZW50X2RvbWFpbgAAAAAAAA4AAAASY2xpZW50LmV4YW1wbGUuY29tAAAAAAAPAAAAFWNsaWVudF9kb21haW5fYWNjb3VudAAAAAAAAA4AAAA4R0FGUUxBWk1HR1pUNEtTRElHQkVJQzVJWE9WSDZJVElGS1VRNVpURFdQM01RV0xHVkpXVEgzVFgAAAAPAAAAC2hvbWVfZG9tYWluAAAAAA4AAAALZXhhbXBsZS5jb20AAAAADwAAAAVub25jZQAAAAAAAA4AAAAMcmFuZG9tLW5vbmNlAAAADwAAAA93ZWJfYXV0aF9kb21haW4AAAAADgAAABBhdXRoLmV4YW1wbGUuY29tAAAADwAAABd3ZWJfYXV0aF9kb21haW5fYWNjb3VudAAAAAAOAAAAOEdDU05SQ1VNNkVERUtTU0JRTklPUDY2T05JTTI2RlZDWVAzR0hZR0Q0TlIzREs0RjYzNVozMldR",
                "AAAAAQAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAACAAAAAAAAAAMAAAAPAAAAB2ZuX2NhbGwAAAAADQAAACBoJLDhyeGyXhpbJFrmlhPP8IpiwZ0PLQh2nUqqm7jG5wAAAA8AAAAMX19jaGVja19hdXRoAAAAEAAAAAEAAAADAAAADQAAACBxtlOMB76x0iUrwTfn57k8z3rdmHxgxraGBqT3uCnvdgAAABAAAAABAAAAAQAAABEAAAABAAAAAgAAAA8AAAAKcHVibGljX2tleQAAAAAADQAAACBSFcZ5UeLUFTqa9zdiEO+0ThI+DS2+aajbYt1SF/PEpQAAAA8AAAAJc2lnbmF0dXJlAAAAAAAADQAAAEBqd7+eTLM/UyBFagJ1mr+WAM185ZWmv/LpYYaFKYnfkr4yaD75fG5mGLnUFafFrCdMsn9mcLOEzCz5of5lMUMGAAAAEAAAAAEAAAABAAAAEAAAAAEAAAACAAAADwAAAAhDb250cmFjdAAAABEAAAABAAAAAwAAAA8AAAAEYXJncwAAABAAAAABAAAAAQAAABEAAAABAAAABwAAAA8AAAAHYWNjb3VudAAAAAAOAAAAOENCVUNKTUhCWkhRM0VYUTJMTVNGVlpVV0NQSDdCQ1RDWUdPUTZMSUlPMk9VVktVM1hERE9PMkhOAAAADwAAAA1jbGllbnRfZG9tYWluAAAAAAAADgAAABJjbGllbnQuZXhhbXBsZS5jb20AAAAAAA8AAAAVY2xpZW50X2RvbWFpbl9hY2NvdW50AAAAAAAADgAAADhHQUZRTEFaTUdHWlQ0S1NESUdCRUlDNUlYT1ZINklUSUZLVVE1WlREV1AzTVFXTEdWSldUSDNUWAAAAA8AAAALaG9tZV9kb21haW4AAAAADgAAAAtleGFtcGxlLmNvbQAAAAAPAAAABW5vbmNlAAAAAAAADgAAAAxyYW5kb20tbm9uY2UAAAAPAAAAD3dlYl9hdXRoX2RvbWFpbgAAAAAOAAAAEGF1dGguZXhhbXBsZS5jb20AAAAPAAAAF3dlYl9hdXRoX2RvbWFpbl9hY2NvdW50AAAAAA4AAAA4R0NTTlJDVU02RURFS1NTQlFOSU9QNjZPTklNMjZGVkNZUDNHSFlHRDROUjNESzRGNjM1WjMyV1EAAAAPAAAACGNvbnRyYWN0AAAAEgAAAAGllitC0H9Kv3DiY2XLacfyHmJzjK0LmtCstctt783dQwAAAA8AAAAHZm5fbmFtZQAAAAAPAAAAD3dlYl9hdXRoX3ZlcmlmeQA=",
                "AAAAAQAAAAAAAAABaCSw4cnhsl4aWyRa5pYTz/CKYsGdDy0Idp1Kqpu4xucAAAACAAAAAAAAAAIAAAAPAAAACWZuX3JldHVybgAAAAAAAA8AAAAMX19jaGVja19hdXRoAAAAAQ==",
                "AAAAAQAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAACAAAAAAAAAAIAAAAPAAAACWZuX3JldHVybgAAAAAAAA8AAAAPd2ViX2F1dGhfdmVyaWZ5AAAAAAE=",
            ],
            "minResourceFee": "188637",
            "results": [
                {
                    "auth": [
                        "AAAAAQAAAAFoJLDhyeGyXhpbJFrmlhPP8IpiwZ0PLQh2nUqqm7jG5yKLTxTml+dTAAFlfwAAABAAAAABAAAAAQAAABEAAAABAAAAAgAAAA8AAAAKcHVibGljX2tleQAAAAAADQAAACBSFcZ5UeLUFTqa9zdiEO+0ThI+DS2+aajbYt1SF/PEpQAAAA8AAAAJc2lnbmF0dXJlAAAAAAAADQAAAEBqd7+eTLM/UyBFagJ1mr+WAM185ZWmv/LpYYaFKYnfkr4yaD75fG5mGLnUFafFrCdMsn9mcLOEzCz5of5lMUMGAAAAAAAAAAGllitC0H9Kv3DiY2XLacfyHmJzjK0LmtCstctt783dQwAAAA93ZWJfYXV0aF92ZXJpZnkAAAAAAQAAABEAAAABAAAABwAAAA8AAAAHYWNjb3VudAAAAAAOAAAAOENCVUNKTUhCWkhRM0VYUTJMTVNGVlpVV0NQSDdCQ1RDWUdPUTZMSUlPMk9VVktVM1hERE9PMkhOAAAADwAAAA1jbGllbnRfZG9tYWluAAAAAAAADgAAABJjbGllbnQuZXhhbXBsZS5jb20AAAAAAA8AAAAVY2xpZW50X2RvbWFpbl9hY2NvdW50AAAAAAAADgAAADhHQUZRTEFaTUdHWlQ0S1NESUdCRUlDNUlYT1ZINklUSUZLVVE1WlREV1AzTVFXTEdWSldUSDNUWAAAAA8AAAALaG9tZV9kb21haW4AAAAADgAAAAtleGFtcGxlLmNvbQAAAAAPAAAABW5vbmNlAAAAAAAADgAAAAxyYW5kb20tbm9uY2UAAAAPAAAAD3dlYl9hdXRoX2RvbWFpbgAAAAAOAAAAEGF1dGguZXhhbXBsZS5jb20AAAAPAAAAF3dlYl9hdXRoX2RvbWFpbl9hY2NvdW50AAAAAA4AAAA4R0NTTlJDVU02RURFS1NTQlFOSU9QNjZPTklNMjZGVkNZUDNHSFlHRDROUjNESzRGNjM1WjMyV1EAAAAA",
                        "AAAAAQAAAAAAAAAApNiKjPEGRUpBg1Dn+85qGa8WosP2Y+DD42Oxq4X2+5174n9h5Cs9wwABZhUAAAAQAAAAAQAAAAEAAAARAAAAAQAAAAIAAAAPAAAACnB1YmxpY19rZXkAAAAAAA0AAAAgpNiKjPEGRUpBg1Dn+85qGa8WosP2Y+DD42Oxq4X2+50AAAAPAAAACXNpZ25hdHVyZQAAAAAAAA0AAABAbiNDkajYz5cUoNr7UgYR1eNLsAj8Mz1C1Qi8pXrvR+u4j8WkLVLH9/C28IDExzJYJ36RXRN/IhsCWJyeO7P1CwAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAAPd2ViX2F1dGhfdmVyaWZ5AAAAAAEAAAARAAAAAQAAAAcAAAAPAAAAB2FjY291bnQAAAAADgAAADhDQlVDSk1IQlpIUTNFWFEyTE1TRlZaVVdDUEg3QkNUQ1lHT1E2TElJTzJPVVZLVTNYRERPTzJITgAAAA8AAAANY2xpZW50X2RvbWFpbgAAAAAAAA4AAAASY2xpZW50LmV4YW1wbGUuY29tAAAAAAAPAAAAFWNsaWVudF9kb21haW5fYWNjb3VudAAAAAAAAA4AAAA4R0FGUUxBWk1HR1pUNEtTRElHQkVJQzVJWE9WSDZJVElGS1VRNVpURFdQM01RV0xHVkpXVEgzVFgAAAAPAAAAC2hvbWVfZG9tYWluAAAAAA4AAAALZXhhbXBsZS5jb20AAAAADwAAAAVub25jZQAAAAAAAA4AAAAMcmFuZG9tLW5vbmNlAAAADwAAAA93ZWJfYXV0aF9kb21haW4AAAAADgAAABBhdXRoLmV4YW1wbGUuY29tAAAADwAAABd3ZWJfYXV0aF9kb21haW5fYWNjb3VudAAAAAAOAAAAOEdDU05SQ1VNNkVERUtTU0JRTklPUDY2T05JTTI2RlZDWVAzR0hZR0Q0TlIzREs0RjYzNVozMldRAAAAAA==",
                        "AAAAAQAAAAAAAAAACwWDLDGzPipDQYJEC6i7qn8iaCqpDuZjs/bIWWaqbTMF/XrhgrGbmwABZX8AAAAQAAAAAQAAAAEAAAARAAAAAQAAAAIAAAAPAAAACnB1YmxpY19rZXkAAAAAAA0AAAAgCwWDLDGzPipDQYJEC6i7qn8iaCqpDuZjs/bIWWaqbTMAAAAPAAAACXNpZ25hdHVyZQAAAAAAAA0AAABAA/tpizKH3Mk/2c1ceLWtXqdmZ03VbWs2nopvZZQ/SiO5jtf06mxR36B8qfOMpR/wMdrQP4wQmUpEIQ/DSjwPDQAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAAPd2ViX2F1dGhfdmVyaWZ5AAAAAAEAAAARAAAAAQAAAAcAAAAPAAAAB2FjY291bnQAAAAADgAAADhDQlVDSk1IQlpIUTNFWFEyTE1TRlZaVVdDUEg3QkNUQ1lHT1E2TElJTzJPVVZLVTNYRERPTzJITgAAAA8AAAANY2xpZW50X2RvbWFpbgAAAAAAAA4AAAASY2xpZW50LmV4YW1wbGUuY29tAAAAAAAPAAAAFWNsaWVudF9kb21haW5fYWNjb3VudAAAAAAAAA4AAAA4R0FGUUxBWk1HR1pUNEtTRElHQkVJQzVJWE9WSDZJVElGS1VRNVpURFdQM01RV0xHVkpXVEgzVFgAAAAPAAAAC2hvbWVfZG9tYWluAAAAAA4AAAALZXhhbXBsZS5jb20AAAAADwAAAAVub25jZQAAAAAAAA4AAAAMcmFuZG9tLW5vbmNlAAAADwAAAA93ZWJfYXV0aF9kb21haW4AAAAADgAAABBhdXRoLmV4YW1wbGUuY29tAAAADwAAABd3ZWJfYXV0aF9kb21haW5fYWNjb3VudAAAAAAOAAAAOEdDU05SQ1VNNkVERUtTU0JRTklPUDY2T05JTTI2RlZDWVAzR0hZR0Q0TlIzREs0RjYzNVozMldRAAAAAA==",
                    ],
                    "xdr": "AAAAAQ==",
                }
            ],
            "stateChanges": [
                {
                    "type": "created",
                    "key": "AAAABgAAAAAAAAAACwWDLDGzPipDQYJEC6i7qn8iaCqpDuZjs/bIWWaqbTMAAAAVBf164YKxm5sAAAAA",
                    "before": None,
                    "after": "AAAAAAAAAAYAAAAAAAAAAAAAAAALBYMsMbM+KkNBgkQLqLuqfyJoKqkO5mOz9shZZqptMwAAABUF/XrhgrGbmwAAAAAAAAABAAAAAA==",
                },
                {
                    "type": "created",
                    "key": "AAAABgAAAAAAAAAApNiKjPEGRUpBg1Dn+85qGa8WosP2Y+DD42Oxq4X2+50AAAAVe+J/YeQrPcMAAAAA",
                    "before": None,
                    "after": "AAAAAAAAAAYAAAAAAAAAAAAAAACk2IqM8QZFSkGDUOf7zmoZrxaiw/Zj4MPjY7Grhfb7nQAAABV74n9h5Cs9wwAAAAAAAAABAAAAAA==",
                },
                {
                    "type": "created",
                    "key": "AAAABgAAAAFoJLDhyeGyXhpbJFrmlhPP8IpiwZ0PLQh2nUqqm7jG5wAAABUii08U5pfnUwAAAAA=",
                    "before": None,
                    "after": "AAAAAAAAAAYAAAAAAAAAAWgksOHJ4bJeGlskWuaWE8/wimLBnQ8tCHadSqqbuMbnAAAAFSKLTxTml+dTAAAAAAAAAAEAAAAA",
                },
            ],
            "latestLedger": 91489,
        },
    }
    signed_entries = build_valid_entries_with_client_domain()
    rpc_mock.expect_response(mock_data)
    resp = await _verify_entries(
        soroban_server,
        signed_entries.to_xdr(),
        SERVER_ACCOUNT,
        home_domains=HOME_DOMAIN,
        web_auth_contract=WEB_AUTH_CONTRACT,
        web_auth_domain=WEB_AUTH_DOMAIN,
        network_passphrase=NETWORK_PASSPHRASE,
    )
    assert resp.web_auth_domain == WEB_AUTH_DOMAIN
    assert resp.web_auth_contract == WEB_AUTH_CONTRACT


async def test_verify_challenge_authorization_entries_failed(soroban_server, rpc_mock):
    mock_data = {
        "jsonrpc": "2.0",
        "id": "ff040b75d5bc423d98c9bbb7120d8103",
        "result": {
            "error": 'HostError: Error(Auth, InvalidInput)\n\nEvent log (newest first):\n   0: [Diagnostic Event] contract:CCSZMK2C2B7UVP3Q4JRWLS3JY7ZB4YTTRSWQXGWQVS24W3PPZXOUHH4R, topics:[error, Error(Auth, InvalidInput)], data:"escalating error to VM trap from failed host function call: require_auth"\n   1: [Diagnostic Event] contract:CCSZMK2C2B7UVP3Q4JRWLS3JY7ZB4YTTRSWQXGWQVS24W3PPZXOUHH4R, topics:[error, Error(Auth, InvalidInput)], data:["signature has expired", GAFQLAZMGGZT4KSDIGBEIC5IXOVH6ITIFKUQ5ZTDWP3MQWLGVJWTH3TX, 91715, 91714]\n   2: [Diagnostic Event] contract:CBUCJMHBZHQ3EXQ2LMSFVZUWCPH7BCTCYGOQ6LIIO2OUVKU3XDDOO2HN, topics:[fn_return, __check_auth], data:Void\n   3: [Diagnostic Event] contract:CCSZMK2C2B7UVP3Q4JRWLS3JY7ZB4YTTRSWQXGWQVS24W3PPZXOUHH4R, topics:[fn_call, CBUCJMHBZHQ3EXQ2LMSFVZUWCPH7BCTCYGOQ6LIIO2OUVKU3XDDOO2HN, __check_auth], data:[Bytes(8272180ea7315f6ecb92446a36c3fa54914282b23c22a19da0b522f5e929af56), [{public_key: Bytes(5215c67951e2d4153a9af7376210efb44e123e0d2dbe69a8db62dd5217f3c4a5), signature: Bytes(25534f6264431dfe235912bf6745a1990ed356eb55476ee83ed7d6c93122eebb0e8ee9a86d97372e37f0798394db9c27232c2512e78b4d41f498a1f8f5aecc0a)}], [[Contract, {args: [{account: "CBUCJMHBZHQ3EXQ2LMSFVZUWCPH7BCTCYGOQ6LIIO2OUVKU3XDDOO2HN", client_domain: "client.example.com", client_domain_account: "GAFQLAZMGGZT4KSDIGBEIC5IXOVH6ITIFKUQ5ZTDWP3MQWLGVJWTH3TX", home_domain: "example.com", nonce: "random-nonce", web_auth_domain: "auth.example.com", web_auth_domain_account: "GCSNRCUM6EDEKSSBQNIOP66ONIM26FVCYP3GHYGD4NR3DK4F635Z32WQ"}], contract: CCSZMK2C2B7UVP3Q4JRWLS3JY7ZB4YTTRSWQXGWQVS24W3PPZXOUHH4R, fn_name: web_auth_verify}]]]\n   4: [Diagnostic Event] topics:[fn_call, CCSZMK2C2B7UVP3Q4JRWLS3JY7ZB4YTTRSWQXGWQVS24W3PPZXOUHH4R, web_auth_verify], data:{account: "CBUCJMHBZHQ3EXQ2LMSFVZUWCPH7BCTCYGOQ6LIIO2OUVKU3XDDOO2HN", client_domain: "client.example.com", client_domain_account: "GAFQLAZMGGZT4KSDIGBEIC5IXOVH6ITIFKUQ5ZTDWP3MQWLGVJWTH3TX", home_domain: "example.com", nonce: "random-nonce", web_auth_domain: "auth.example.com", web_auth_domain_account: "GCSNRCUM6EDEKSSBQNIOP66ONIM26FVCYP3GHYGD4NR3DK4F635Z32WQ"}\n',
            "events": [
                "AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAADAAAADwAAAAdmbl9jYWxsAAAAAA0AAAAgpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAAPAAAAD3dlYl9hdXRoX3ZlcmlmeQAAAAARAAAAAQAAAAcAAAAPAAAAB2FjY291bnQAAAAADgAAADhDQlVDSk1IQlpIUTNFWFEyTE1TRlZaVVdDUEg3QkNUQ1lHT1E2TElJTzJPVVZLVTNYRERPTzJITgAAAA8AAAANY2xpZW50X2RvbWFpbgAAAAAAAA4AAAASY2xpZW50LmV4YW1wbGUuY29tAAAAAAAPAAAAFWNsaWVudF9kb21haW5fYWNjb3VudAAAAAAAAA4AAAA4R0FGUUxBWk1HR1pUNEtTRElHQkVJQzVJWE9WSDZJVElGS1VRNVpURFdQM01RV0xHVkpXVEgzVFgAAAAPAAAAC2hvbWVfZG9tYWluAAAAAA4AAAALZXhhbXBsZS5jb20AAAAADwAAAAVub25jZQAAAAAAAA4AAAAMcmFuZG9tLW5vbmNlAAAADwAAAA93ZWJfYXV0aF9kb21haW4AAAAADgAAABBhdXRoLmV4YW1wbGUuY29tAAAADwAAABd3ZWJfYXV0aF9kb21haW5fYWNjb3VudAAAAAAOAAAAOEdDU05SQ1VNNkVERUtTU0JRTklPUDY2T05JTTI2RlZDWVAzR0hZR0Q0TlIzREs0RjYzNVozMldR",
                "AAAAAAAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAACAAAAAAAAAAMAAAAPAAAAB2ZuX2NhbGwAAAAADQAAACBoJLDhyeGyXhpbJFrmlhPP8IpiwZ0PLQh2nUqqm7jG5wAAAA8AAAAMX19jaGVja19hdXRoAAAAEAAAAAEAAAADAAAADQAAACCCchgOpzFfbsuSRGo2w/pUkUKCsjwioZ2gtSL16SmvVgAAABAAAAABAAAAAQAAABEAAAABAAAAAgAAAA8AAAAKcHVibGljX2tleQAAAAAADQAAACBSFcZ5UeLUFTqa9zdiEO+0ThI+DS2+aajbYt1SF/PEpQAAAA8AAAAJc2lnbmF0dXJlAAAAAAAADQAAAEAlU09iZEMd/iNZEr9nRaGZDtNW61VHbug+19bJMSLuuw6O6ahtlzcuN/B5g5TbnCcjLCUS54tNQfSYofj1rswKAAAAEAAAAAEAAAABAAAAEAAAAAEAAAACAAAADwAAAAhDb250cmFjdAAAABEAAAABAAAAAwAAAA8AAAAEYXJncwAAABAAAAABAAAAAQAAABEAAAABAAAABwAAAA8AAAAHYWNjb3VudAAAAAAOAAAAOENCVUNKTUhCWkhRM0VYUTJMTVNGVlpVV0NQSDdCQ1RDWUdPUTZMSUlPMk9VVktVM1hERE9PMkhOAAAADwAAAA1jbGllbnRfZG9tYWluAAAAAAAADgAAABJjbGllbnQuZXhhbXBsZS5jb20AAAAAAA8AAAAVY2xpZW50X2RvbWFpbl9hY2NvdW50AAAAAAAADgAAADhHQUZRTEFaTUdHWlQ0S1NESUdCRUlDNUlYT1ZINklUSUZLVVE1WlREV1AzTVFXTEdWSldUSDNUWAAAAA8AAAALaG9tZV9kb21haW4AAAAADgAAAAtleGFtcGxlLmNvbQAAAAAPAAAABW5vbmNlAAAAAAAADgAAAAxyYW5kb20tbm9uY2UAAAAPAAAAD3dlYl9hdXRoX2RvbWFpbgAAAAAOAAAAEGF1dGguZXhhbXBsZS5jb20AAAAPAAAAF3dlYl9hdXRoX2RvbWFpbl9hY2NvdW50AAAAAA4AAAA4R0NTTlJDVU02RURFS1NTQlFOSU9QNjZPTklNMjZGVkNZUDNHSFlHRDROUjNESzRGNjM1WjMyV1EAAAAPAAAACGNvbnRyYWN0AAAAEgAAAAGllitC0H9Kv3DiY2XLacfyHmJzjK0LmtCstctt783dQwAAAA8AAAAHZm5fbmFtZQAAAAAPAAAAD3dlYl9hdXRoX3ZlcmlmeQA=",
                "AAAAAAAAAAAAAAABaCSw4cnhsl4aWyRa5pYTz/CKYsGdDy0Idp1Kqpu4xucAAAACAAAAAAAAAAIAAAAPAAAACWZuX3JldHVybgAAAAAAAA8AAAAMX19jaGVja19hdXRoAAAAAQ==",
                "AAAAAAAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAACAAAAAAAAAAIAAAAPAAAABWVycm9yAAAAAAAAAgAAAAkAAAACAAAAEAAAAAEAAAAEAAAADgAAABVzaWduYXR1cmUgaGFzIGV4cGlyZWQAAAAAAAASAAAAAAAAAAALBYMsMbM+KkNBgkQLqLuqfyJoKqkO5mOz9shZZqptMwAAAAMAAWZDAAAAAwABZkI=",
                "AAAAAAAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAACAAAAAAAAAAIAAAAPAAAABWVycm9yAAAAAAAAAgAAAAkAAAACAAAADgAAAEhlc2NhbGF0aW5nIGVycm9yIHRvIFZNIHRyYXAgZnJvbSBmYWlsZWQgaG9zdCBmdW5jdGlvbiBjYWxsOiByZXF1aXJlX2F1dGg=",
                "AAAAAAAAAAAAAAABpZYrQtB/Sr9w4mNly2nH8h5ic4ytC5rQrLXLbe/N3UMAAAACAAAAAAAAAAEAAAAPAAAAA2xvZwAAAAAQAAAAAQAAAAMAAAAOAAAAHlZNIGNhbGwgdHJhcHBlZCB3aXRoIEhvc3RFcnJvcgAAAAAADwAAAA93ZWJfYXV0aF92ZXJpZnkAAAAAAgAAAAkAAAAC",
            ],
            "latestLedger": 91715,
        },
    }

    signed_entries = build_valid_entries_with_client_domain()
    rpc_mock.expect_response(mock_data)
    with pytest.raises(
        InvalidSep45ChallengeError,
        match=r"Validation failed during simulation",
    ):
        await _verify_entries(
            soroban_server,
            signed_entries.to_xdr(),
            SERVER_ACCOUNT,
            home_domains=HOME_DOMAIN,
            web_auth_contract=WEB_AUTH_CONTRACT,
            web_auth_domain=WEB_AUTH_DOMAIN,
            network_passphrase=NETWORK_PASSPHRASE,
        )


def test_challenge_authorization_entries_client_domain_without_account():
    """Test that ChallengeAuthorizationEntries raises error when client_domain is provided without client_domain_account."""
    entries = build_valid_entries_with_client_domain()
    with pytest.raises(
        ValueError,
        match=r"client_domain and client_domain_account must both be provided or both be None.",
    ):
        ChallengeAuthorizationEntries(
            authorization_entries=entries,
            client_account_id=CLIENT_CONTRACT_ACCOUNT,
            matched_home_domain=HOME_DOMAIN,
            nonce=NONCE,
            web_auth_domain=WEB_AUTH_DOMAIN,
            server_account_id=SERVER_ACCOUNT,
            web_auth_contract=WEB_AUTH_CONTRACT,
            client_domain=CLIENT_DOMAIN,
            client_domain_account=None,
        )


def test_challenge_authorization_entries_client_domain_account_without_domain():
    """Test that ChallengeAuthorizationEntries raises error when client_domain_account is provided without client_domain."""
    entries = build_valid_entries_with_client_domain()
    with pytest.raises(
        ValueError,
        match=r"client_domain and client_domain_account must both be provided or both be None.",
    ):
        ChallengeAuthorizationEntries(
            authorization_entries=entries,
            client_account_id=CLIENT_CONTRACT_ACCOUNT,
            matched_home_domain=HOME_DOMAIN,
            nonce=NONCE,
            web_auth_domain=WEB_AUTH_DOMAIN,
            server_account_id=SERVER_ACCOUNT,
            web_auth_contract=WEB_AUTH_CONTRACT,
            client_domain=None,
            client_domain_account=CLIENT_DOMAIN_ACCOUNT,
        )
